name: Release - Module

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-countries,codbex-countries-data
      packages-build: codbex-countries
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-countries - ${{ inputs.release-version }}
  
        Countries Application Module
  
        ## Installation
  
        ```
        npm install @codbex/codbex-countries@${{ inputs.release-version }}
        npm install @codbex/codbex-countries-data@${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-countries/gen/](http://localhost:8080/services/web/codbex-countries/gen/) - Admin Panel
    secrets: inherit
