name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/application-release.yaml@main
    with:
      application-name: codbex-countries
      release-version: ${{ inputs.release-version }}
      release-package: true
      release-package-locations: codbex-countries,codbex-countries-data
      release-package-build-locations: codbex-countries
      release-content: |
        ## codbex-countries - ${{ inputs.release-version }}
  
        Countries Application Module
  
        ## Deployment
  
        ```
        docker run --name codbex-countries \
        --rm -p 8080:8080 -p 8081:8081 \
        ghcr.io/codbex/codbex-countries:${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-countries/gen/](http://localhost:8080/services/web/codbex-countries/gen/) - Admin Panel
    secrets: inherit
